// Project Name: TGP Consumer Webapp
// -----------------------------
// Author: Priyanshu Chauhan
// Last Updated: 9/8/2021, 8:00:00 am

// actions for the getFeaturedEvents(GET)
export const GET_FEATURED_EVENTS = "GET_FEATURED_EVENTS"
export const GET_FEATURED_EVENTS_SUCCESS = "GET_FEATURED_EVENTS_SUCCESS"
export const GET_FEATURED_EVENTS_FAILURE = "GET_FEATURED_EVENTS_FAILURE"
export const GET_FEATURED_EVENTS_INIT = "GET_FEATURED_EVENTS_INIT"

// actions for the getEventDetails(GET) - For details of an active events
export const GET_EVENT_DETAILS = "GET_EVENT_DETAILS"
export const GET_EVENT_DETAILS_SUCCESS = "GET_EVENT_DETAILS_SUCCESS"
export const GET_EVENT_DETAILS_FAILURE = "GET_EVENT_DETAILS_FAILURE"
export const GET_EVENT_DETAILS_INIT = "GET_EVENT_DETAILS_INIT"

// actions for the getSuggestedEvents(GET)
export const GET_SUGGESTED_EVENTS = "GET_SUGGESTED_EVENTS"
export const GET_SUGGESTED_EVENTS_SUCCESS = "GET_SUGGESTED_EVENTS_SUCCESS"
export const GET_SUGGESTED_EVENTS_FAILURE = "GET_SUGGESTED_EVENTS_FAILURE"
export const GET_SUGGESTED_EVENTS_INIT = "GET_SUGGESTED_EVENTS_INIT"

// actions for the getFeaturedEvents(GET)
export const GET_ACTIVE_EVENTS_LIST = "GET_ACTIVE_EVENTS_LIST"
export const GET_ACTIVE_EVENTS_LIST_SUCCESS = "GET_ACTIVE_EVENTS_LIST_SUCCESS"
export const GET_ACTIVE_EVENTS_LIST_FAILURE = "GET_ACTIVE_EVENTS_LIST_FAILURE"
export const GET_ACTIVE_EVENTS_LIST_INIT = "GET_ACTIVE_EVENTS_LIST_INIT"