export const GET_ARTIST_PROFILE = "GET_ARTIST_PROFILE"
export const GET_ARTIST_PROFILE_SUCCESS = "GET_ARTIST_PROFILE_SUCCESS"
export const GET_ARTIST_PROFILE_FAILURE = "GET_ARTIST_PROFILE_FAILURE"
export const GET_ARTIST_PROFILE_INIT = "GET_ARTIST_PROFILE_INIT"

export const GET_ARTISTS_LIST = "GET_ARTISTS_LIST"
export const GET_ARTISTS_LIST_SUCCESS = "GET_ARTISTS_LIST_SUCCESS"
export const GET_ARTISTS_LIST_FAILURE = "GET_ARTISTS_LIST_FAILURE"
export const GET_ARTISTS_LIST_INIT = "GET_ARTISTS_LIST_INIT"

export const GET_ARTIST_NAME_LIST = "GET_ARTIST_NAME_LIST"
export const GET_ARTIST_NAME_LIST_SUCCESS = "GET_ARTIST_NAME_LIST_SUCCESS"
export const GET_ARTIST_NAME_LIST_FAILURE = "GET_ARTIST_NAME_LIST_FAILURE"
export const GET_ARTIST_NAME_LIST_INIT = "GET_ARTIST_NAME_LIST_INIT"

export const GET_FEATURED_ARTISTS = "GET_FEATURED_ARTISTS"
export const GET_FEATURED_ARTISTS_SUCCESS = "GET_FEATURED_ARTISTS_SUCCESS"
export const GET_FEATURED_ARTISTS_FAILURE = "GET_FEATURED_ARTISTS_FAILURE"
export const GET_FEATURED_ARTISTS_INIT = "GET_FEATURED_ARTISTS_INIT"

