// Project Name: TGP Consumer Webapp
// -----------------------------
// Authors: Priyanshu Chauhan, Prince Maurya
// Last Updated:   29/7/2021, 12:30:00 pm

// actions for the getArtwork(GET)
export const GET_ONE_ARTWORK = "GET_ONE_ARTWORK"
export const GET_ONE_ARTWORK_SUCCESS = "GET_ONE_ARTWORK_SUCCESS"
export const GET_ONE_ARTWORK_FAILURE = "GET_ONE_ARTWORK_FAILURE"
export const GET_ONE_ARTWORK_INIT = "GET_ONE_ARTWORK_INIT"

// actions for the getSimilarArtwork(GET)
export const GET_SIMILAR_ARTWORK = "GET_SIMILAR_ARTWORK"
export const GET_SIMILAR_ARTWORK_SUCCESS = "GET_SIMILAR_ARTWORK_SUCCESS"
export const GET_SIMILAR_ARTWORK_FAILURE = "GET_SIMILAR_ARTWORK_FAILURE"
export const GET_SIMILAR_ARTWORK_INIT = "GET_SIMILAR_ARTWORK_INIT"

// actions for the getDedicatedArtwork(POST) - Specific to a particular artist
export const GET_DEDICATED_ARTWORK = "GET_DEDICATED_ARTWORK"
export const GET_DEDICATED_ARTWORK_SUCCESS = "GET_DEDICATED_ARTWORK_SUCCESS"
export const GET_DEDICATED_ARTWORK_FAILURE = "GET_DEDICATED_ARTWORK_FAILURE"
export const GET_DEDICATED_ARTWORK_INIT = "GET_DEDICATED_ARTWORK_INIT"

// actions for the getSeriesArtwork(GET) - Artwork in a perticular series
export const GET_SERIES_ARTWORK = "GET_SERIES_ARTWORK"
export const GET_SERIES_ARTWORK_SUCCESS = "GET_SERIES_ARTWORK_SUCCESS"
export const GET_SERIES_ARTWORK_FAILURE = "GET_SERIES_ARTWORK_FAILURE"
export const GET_SERIES_ARTWORK_INIT = "GET_SERIES_ARTWORK_INIT"

// actions for Report Artwork(POST)
export const REPORT_ARTWORK = 'REPORT_ARTWORK';
export const REPORT_ARTWORK_SUCCESS =
  'REPORT_ARTWORK_SUCCESS';
export const REPORT_ARTWORK_FAILURE =
  'REPORT_ARTWORK_FAILURE';
export const REPORT_ARTWORK_INIT = 'REPORT_ARTWORK_INIT';

// actions for Report Options (GET)
export const GET_REPORT_OPTIONS = 'GET_REPORT_OPTIONS';
export const GET_REPORT_OPTIONS_SUCCESS =
  'GET_REPORT_OPTIONS_SUCCESS';
export const GET_REPORT_OPTIONS_FAILURE =
  'GET_REPORT_OPTIONS_FAILURE';
export const GET_REPORT_OPTIONS_INIT =
  'GET_REPORT_OPTIONS_INIT';