export const CREATE_CONSUMER = "CREATE_CONSUMER"
export const CREATE_CONSUMER_SUCCESS = "CREATE_CONSUMER_SUCCESS"
export const CREATE_CONSUMER_FAILURE = "CREATE_CONSUMER_FAILURE"
export const CREATE_CONSUMER_INIT = "CREATE_CONSUMER_INIT"

export const SET_PASSWORD = "SET_PASSWORD"
export const SET_PASSWORD_SUCCESS = "SET_PASSWORD_SUCCESS"
export const SET_PASSWORD_FAILURE = "SET_PASSWORD_FAILURE"
export const SET_PASSWORD_INIT = "SET_PASSWORD_INIT"

export const SET_TNC_ACCEPTANCE = "SET_TNC_ACCEPTANCE"
export const SET_TNC_ACCEPTANCE_SUCCESS = "SET_TNC_ACCEPTANCE_SUCCESS"
export const SET_TNC_ACCEPTANCE_FAILURE = "SET_TNC_ACCEPTANCE_FAILURE"
export const SET_TNC_ACCEPTANCE_INIT = "SET_TNC_ACCEPTANCE_INIT"
