export const LOGIN_SOCIAL_MEDIA = "LOGIN_SOCIAL_MEDIA"
export const LOGIN_SOCIAL_MEDIA_SUCCESS = "LOGIN_SOCIAL_MEDIA_SUCCESS"
export const LOGIN_SOCIAL_MEDIA_FAILURE = "LOGIN_SOCIAL_MEDIA_FAILURE"
export const LOGIN_SOCIAL_MEDIA_INIT = "LOGIN_SOCIAL_MEDIA_INIT"

export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE"
export const LOGIN_USER_INIT = "LOGIN_USER_INIT"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE"
export const LOGOUT_USER_INIT = "LOGOUT_USER_INIT"


export const GET_USER_DETAILS = "GET_USER_DETAILS"
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS"
export const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE"
export const GET_USER_DETAILS_INIT = "GET_USER_DETAILS_INIT"

export const STORE_INIT = "STORE_INIT"
// export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';

export const REGISTER_CUSTOMER = "REGISTER_CUSTOMER"
export const REGISTER_CUSTOMER_SUCCESS = "REGISTER_CUSTOMER_SUCCESS"
export const REGISTER_CUSTOMER_FAILURE = "REGISTER_CUSTOMER_FAILURE"
export const REGISTER_CUSTOMER_INIT = "REGISTER_CUSTOMER_INIT"