export const FORGOT_PASSWORD_EMAIL = "FORGOT_PASSWORD_EMAIL"
export const FORGOT_PASSWORD_EMAIL_SUCCESS = "FORGOT_PASSWORD_EMAIL_SUCCESS"
export const FORGOT_PASSWORD_EMAIL_FAILURE = "FORGOT_PASSWORD_EMAIL_FAILURE"
export const FORGOT_PASSWORD_EMAIL_INIT = "FORGOT_PASSWORD_EMAIL_INIT"

export const CHECK_RESET_IDENTIFIER = "CHECK_RESET_IDENTIFIER"
export const CHECK_RESET_IDENTIFIER_SUCCESS = "CHECK_RESET_IDENTIFIER_SUCCESS"
export const CHECK_RESET_IDENTIFIER_FAILURE = "CHECK_RESET_IDENTIFIER_FAILURE"
export const CHECK_RESET_IDENTIFIER_INIT = "CHECK_RESET_IDENTIFIER_INIT"